/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaoGeralRouteImport } from './routes/visao-geral'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as DadosTesouroRouteImport } from './routes/dados-tesouro'
import { Route as DadosAlespRouteImport } from './routes/dados-alesp'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const VisaoGeralRoute = VisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosTesouroRoute = DadosTesouroRouteImport.update({
  id: '/dados-tesouro',
  path: '/dados-tesouro',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosAlespRoute = DadosAlespRouteImport.update({
  id: '/dados-alesp',
  path: '/dados-alesp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dados-alesp': typeof DadosAlespRoute
  '/dados-tesouro': typeof DadosTesouroRoute
  '/metodologia': typeof MetodologiaRoute
  '/visao-geral': typeof VisaoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dados-alesp': typeof DadosAlespRoute
  '/dados-tesouro': typeof DadosTesouroRoute
  '/metodologia': typeof MetodologiaRoute
  '/visao-geral': typeof VisaoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dados-alesp': typeof DadosAlespRoute
  '/dados-tesouro': typeof DadosTesouroRoute
  '/metodologia': typeof MetodologiaRoute
  '/visao-geral': typeof VisaoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/dados-alesp'
    | '/dados-tesouro'
    | '/metodologia'
    | '/visao-geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/dados-alesp'
    | '/dados-tesouro'
    | '/metodologia'
    | '/visao-geral'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/dados-alesp'
    | '/dados-tesouro'
    | '/metodologia'
    | '/visao-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DadosAlespRoute: typeof DadosAlespRoute
  DadosTesouroRoute: typeof DadosTesouroRoute
  MetodologiaRoute: typeof MetodologiaRoute
  VisaoGeralRoute: typeof VisaoGeralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visao-geral': {
      id: '/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof VisaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-tesouro': {
      id: '/dados-tesouro'
      path: '/dados-tesouro'
      fullPath: '/dados-tesouro'
      preLoaderRoute: typeof DadosTesouroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-alesp': {
      id: '/dados-alesp'
      path: '/dados-alesp'
      fullPath: '/dados-alesp'
      preLoaderRoute: typeof DadosAlespRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DadosAlespRoute: DadosAlespRoute,
  DadosTesouroRoute: DadosTesouroRoute,
  MetodologiaRoute: MetodologiaRoute,
  VisaoGeralRoute: VisaoGeralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
